name: CI
'on': push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run : pwd
    - run : ll
    - uses: vimtor/action-zip@v1
      with:
       files: .
       recursive: true
       dest: builddefs-qmake-package.zip
    - uses: actions/upload-artifact@v3
      with:
        name: builddefs-qmake-package
        path: builddefs-qmake-package.zip

    
