name: CI
on:
  push:
    branches:
      - master
      - develop
      - '/releases/**'
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
      
env: 
  tag_version: ${{ github.ref_name == 'develop' && '0.0.0' || github.ref_name }}  
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run : cd .. && mkdir builddefs-qmake-package && cp -r builddefs-qmake/ builddefs-qmake-package/builddefs-qmake && mv builddefs-qmake-package builddefs-qmake/builddefs-qmake-package && cd - 
    - uses: actions/upload-artifact@v3
      with:
        name: builddefs-qmake-package
        path: builddefs-qmake-package
    #- run : rm -rf builddefs-qmake-package
    - run : ll
   
    
    # # Delete previous latest version 
    # - name: delete previous latest version
      # uses: dev-drprasad/delete-tag-and-release@v1.0
      # with:
        # tag_name: builddefs-qmake-${{ env.tag_version }}
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        # delete_release: true
    
    # - uses: "marvinpinto/action-automatic-releases@latest"
      # with:
        # repo_token: ${{ secrets.GITHUB_TOKEN }}
        # automatic_release_tag: builddefs-qmake-${{ env.tag_version }}
        # prerelease: true
        # title: xpcf/${{ env.tag_version }}/win
        # files: |
          # xpcf_${{ env.tag_version }}_x86_64_static_release.zip
          # xpcf_${{ env.tag_version }}_x86_64_shared_release.zip

    
