name: CI
on:
  push:
    branches:
      - master
      - develop
      - '/releases/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run : ls -l
    #- run : cd .. && ls -l && zip builddefs-qmake-package.zip -r builddefs-qmake && cd -
    #- run : mv ../builddefs-qmake-package.zip . 
    #- run : ls -l
    - run : cd ..
    - run : cd .. && mkdir builddefs-qmake-package && cp -r builddefs-qmake/ builddefs-qmake-package/builddefs-qmake && mv builddefs-qmake-package builddefs-qmake/builddefs-qmake-package && cd - 
    #- run : mv ../builddefs-qmake-package.zip . 
    
    - uses: actions/upload-artifact@v3
      with:
        name: builddefs-qmake-package
        path: builddefs-qmake-package

    
